name: Cypress Tests

on:
  push:
    branches:
      - main
      - master
      - 'feature/*'
  pull_request:
    branches:
      - main
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        browser: [chrome, firefox] # Add browsers to the matrix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress tests in ${{ matrix.browser }}
        run: npx cypress run --browser ${{ matrix.browser }}

      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
         name: cypress-videos-${{ matrix.browser }}
         path: cypress/videos

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
         name: cypress-screenshots-${{ matrix.browser }}
         path: cypress/screenshots
